NAME = ft_display_file
SRC = ft_display_file.c
OBJ = ft_display_file.o
FLAGS = -Wall -Wextra -Werror
all:$(NAME)
$(NAME):
	gcc -o $(NAME) $(SRC)
clean:
	rm -f $(OBJ)
fclean:clean
	rm -f $(NAME)
re:
	fclean re
